config/routes.rb
# frozen_string_literal: true

require 'api_constraints'

Rails.application.routes.draw do
  mount RapidRack::Engine => '/auth'

  get '/dashboard' => 'dashboard#index', :as => 'dashboard'
  root to: 'welcome#index'
  get 'health' => 'health#show'
  # Browsers often request /favicon.ico. This controller redirects to the actual favicon.
  resource :favicon, only: :show

  scope '/federation_reports' do
    get 'federation_growth_report' => 'federation_reports#federation_growth_report',
        :as => :public_federation_growth_report

    get 'federated_sessions_report' => 'federation_reports#federated_sessions_report',
        :as => :public_federated_sessions_report

    get 'daily_demand_report' => 'federation_reports#daily_demand_report', :as => :public_daily_demand_report
  end

  scope '/compliance_reports' do
    def match_report(prefix, name, http_verbs)
      match "/#{prefix}_#{name}", to: "compliance_reports##{prefix}_#{name}", via: http_verbs, as: :"#{prefix}_#{name}"
    end

    match_report('service_provider', 'compatibility_report', %i[get post])
    match_report('identity_provider', 'attributes_report', :get)
    match_report('attribute', 'identity_providers_report', %i[get post])
    match_report('attribute', 'service_providers_report', %i[get post])
  end

  get '/admin_reports' => 'administrator_reports#index', :as => :admin_reports

  scope '/admin_reports' do
    def match_report(name, http_verbs)
      match "/#{name}", to: "administrator_reports##{name}", via: http_verbs, as: :"admin_#{name}"
    end

    match_report('subscriber_registrations_report', %i[get post])
    match_report('federation_growth_report', %i[get post])
    match_report('daily_demand_report', %i[get post])
    match_report('federated_sessions_report', %i[get post])
    match_report('identity_provider_utilization_report', %i[get post])
    match_report('service_provider_utilization_report', %i[get post])
  end

  get '/subscriber_reports' => 'subscriber_reports_dashboard#index', :as => :subscriber_reports

  scope '/subscriber_reports' do
    def match_report(prefix, name, http_verbs)
      match "/#{prefix}_#{name}", to: "#{prefix}_reports##{name}", via: http_verbs, as: :"#{prefix}_#{name}"
    end

    match_report('identity_provider', 'sessions_report', %i[get post])
    match_report('identity_provider', 'daily_demand_report', %i[get post])
    match_report('identity_provider', 'destination_services_report', %i[get post])

    match_report('service_provider', 'sessions_report', %i[get post])
    match_report('service_provider', 'daily_demand_report', %i[get post])
    match_report('service_provider', 'source_identity_providers_report', %i[get post])
  end

  get 'automated_report/:identifier', to: 'automated_report_instances#show', as: :automated_report

  scope '/automated_reports' do
    get '/' => 'automated_reports#index', :as => :automated_reports
    post '/' => 'automated_reports#subscribe'
    delete '/:identifier' => 'automated_reports#destroy'
  end
end

RapidRack::Engine.routes.draw do
  opts = Rails.application.config.reporting_service.rapid_connect[:rack]
  authenticator = opts[:authenticator].constantize.new(opts)

  mount authenticator => ''
end

app/controllers/identity_provider_reports_controller.rb
# frozen_string_literal: true

class IdentityProviderReportsController < SubscriberReports
  def sessions_report
    report_type = IdentityProviderSessionsReport
    @data = output(report_type, scaled_steps) if params[:entity_id].present?
  end

  def daily_demand_report
    report_type = IdentityProviderDailyDemandReport
    @data = output(report_type) if params[:entity_id].present?
  end

  def destination_services_report
    report_type = IdentityProviderDestinationServicesReport
    @data = output(report_type) if params[:entity_id].present?
  end

  private

  def model_object
    IdentityProvider
  end
end

app/views/identity_provider_reports/_form.html.slim
- entity_type = 'identity provider'

-if !@entities.blank?
  = render(partial: 'shared/subscriber_report_form', locals: { entity_type: entity_type })

  - if @data
    = render(partial: 'shared/report_output', locals: { data: @data })

-else
  = render(partial: 'shared/no_report_permission', locals: { entity_type: entity_type })

app/views/identity_provider_reports/daily_demand_report.html.slim
= breadcrumbs({ 'Subscriber Reports' => subscriber_reports_path },
                'Daily Demand Report')

= render(partial: 'shared/flash_message',
       locals: { flash_header: 'Successfully Subscribed' })

- if @data
  = render(partial: 'shared/subscribe_form',
           locals: { target: @entity_id,
                     report_class: 'IdentityProviderDailyDemandReport' })

h1 Identity Provider Daily Demand  Report

p Graphs the daily trend of sessions established for an Identity Provider,
  highlighting which time of day users are most active

= render(partial: 'form')

app/views/identity_provider_reports/destination_services_report.html.slim
= breadcrumbs({ 'Subscriber Reports' => subscriber_reports_path },
                'Destination Services Report')

= render(partial: 'shared/flash_message',
       locals: { flash_header: 'Successfully Subscribed' })

- if @data
  = render(partial: 'shared/subscribe_form',
           locals: { target: @entity_id,
                     report_class: 'IdentityProviderDestinationServicesReport' })

h1 Identity Provider Destination Services Report

p Graphs the number of sessions from an Identity Provider going to each Service.

= render(partial: 'form')

app/views/identity_provider_reports/sessions_report.html.slim
= breadcrumbs({ 'Subscriber Reports' => subscriber_reports_path },
                'Sessions Report')

= render(partial: 'shared/flash_message',
       locals: { flash_header: 'Successfully Subscribed' })

- if @data
  = render(partial: 'shared/subscribe_form',
           locals: { target: @entity_id,
                     report_class: 'IdentityProviderSessionsReport' })

h1 Identity Provider Sessions Report

p Graphs the hourly number of sessions established for an
  Identity Provider

= render(partial: 'form')