config/routes.rb
# frozen_string_literal: true

require 'api_constraints'

Rails.application.routes.draw do
  mount RapidRack::Engine => '/auth'

  get '/dashboard' => 'dashboard#index', :as => 'dashboard'
  root to: 'welcome#index'
  get 'health' => 'health#show'
  # Browsers often request /favicon.ico. This controller redirects to the actual favicon.
  resource :favicon, only: :show

  scope '/federation_reports' do
    get 'federation_growth_report' => 'federation_reports#federation_growth_report',
        :as => :public_federation_growth_report

    get 'federated_sessions_report' => 'federation_reports#federated_sessions_report',
        :as => :public_federated_sessions_report

    get 'daily_demand_report' => 'federation_reports#daily_demand_report', :as => :public_daily_demand_report
  end

  scope '/compliance_reports' do
    def match_report(prefix, name, http_verbs)
      match "/#{prefix}_#{name}", to: "compliance_reports##{prefix}_#{name}", via: http_verbs, as: :"#{prefix}_#{name}"
    end

    match_report('service_provider', 'compatibility_report', %i[get post])
    match_report('identity_provider', 'attributes_report', :get)
    match_report('attribute', 'identity_providers_report', %i[get post])
    match_report('attribute', 'service_providers_report', %i[get post])
  end

  get '/admin_reports' => 'administrator_reports#index', :as => :admin_reports

  scope '/admin_reports' do
    def match_report(name, http_verbs)
      match "/#{name}", to: "administrator_reports##{name}", via: http_verbs, as: :"admin_#{name}"
    end

    match_report('subscriber_registrations_report', %i[get post])
    match_report('federation_growth_report', %i[get post])
    match_report('daily_demand_report', %i[get post])
    match_report('federated_sessions_report', %i[get post])
    match_report('identity_provider_utilization_report', %i[get post])
    match_report('service_provider_utilization_report', %i[get post])
  end

  get '/subscriber_reports' => 'subscriber_reports_dashboard#index', :as => :subscriber_reports

  scope '/subscriber_reports' do
    def match_report(prefix, name, http_verbs)
      match "/#{prefix}_#{name}", to: "#{prefix}_reports##{name}", via: http_verbs, as: :"#{prefix}_#{name}"
    end

    match_report('identity_provider', 'sessions_report', %i[get post])
    match_report('identity_provider', 'daily_demand_report', %i[get post])
    match_report('identity_provider', 'destination_services_report', %i[get post])

    match_report('service_provider', 'sessions_report', %i[get post])
    match_report('service_provider', 'daily_demand_report', %i[get post])
    match_report('service_provider', 'source_identity_providers_report', %i[get post])
  end

  get 'automated_report/:identifier', to: 'automated_report_instances#show', as: :automated_report

  scope '/automated_reports' do
    get '/' => 'automated_reports#index', :as => :automated_reports
    post '/' => 'automated_reports#subscribe'
    delete '/:identifier' => 'automated_reports#destroy'
  end
end

RapidRack::Engine.routes.draw do
  opts = Rails.application.config.reporting_service.rapid_connect[:rack]
  authenticator = opts[:authenticator].constantize.new(opts)

  mount authenticator => ''
end

app/controllers/administrator_reports_controller.rb
# frozen_string_literal: true

class AdministratorReportsController < ApplicationController
  include Steps

  before_action { check_access! 'admin:report' }
  before_action :set_range_params, except: %i[subscriber_registrations_report index]
  before_action :set_source, except: %i[subscriber_registrations_report federation_growth_report index]

  def index
  end

  def subscriber_registrations_report
    return if params[:identifier].blank?

    @identifier = params[:identifier]
    report = SubscriberRegistrationsReport.new(@identifier)
    @data = JSON.generate(report.generate)
  end

  def federation_growth_report
    return if params[:start].blank? || params[:end].blank?

    report = FederationGrowthReport.new(start, finish)
    @data = JSON.generate(report.generate)
  end

  def daily_demand_report
    return if params[:start].blank? || params[:end].blank?

    report = DailyDemandReport.new(start, finish, @source)
    @data = JSON.generate(report.generate)
  end

  def federated_sessions_report
    return if params[:start].blank? || params[:end].blank?

    report = FederatedSessionsReport.new(start, finish, scaled_steps, @source)
    @data = JSON.generate(report.generate)
  end

  def identity_provider_utilization_report
    return if params[:start].blank? || params[:end].blank?

    report = IdentityProviderUtilizationReport.new(start, finish, @source)
    @data = JSON.generate(report.generate)
  end

  def service_provider_utilization_report
    return if params[:start].blank? || params[:end].blank?

    report = ServiceProviderUtilizationReport.new(start, finish, @source)
    @data = JSON.generate(report.generate)
  end

  private

  def set_source
    return nil if params[:source].blank?

    @source = params[:source]
  end
end

app/views/administrator_reports/_form.html.slim
- start_date = @start ? @start : Time.zone.now.beginning_of_month - 1.month
- end_date = @end ? @end : Time.zone.now.beginning_of_month
- source = @source
- source = Rails.application.config.reporting_service.default_session_source if source.blank?
- source = 'DS' if source.blank?
- source_options = ReportsSharedMethods.source_options

= form_tag({}, id: 'report-form') do
  = field_block do
    = label_tag(:start) do
      | from

    = date_field_tag :start, value = start_date, placeholder: 'click here to pick a date'

  = field_block do
    = label_tag(:end) do
      | to

    = date_field_tag :end, value = end_date, placeholder: 'click here to pick a date'

  - if not report_class.eql? 'FederationGrowthReport'
    = field_block do
      = label_tag(:source) do
        | session data source

      = select_tag :source, options_for_select(source_options, source), placeholder: 'select the data source'

  = button_tag(type: 'submit', class: 'btn-lg btn-primary') do
    => icon_tag('ok')
    | Generate

= validate_form('#report-form', nil) do |v|
  - v.validate_field(:start, required: { message: 'Please pick start date' })
  - v.validate_field(:start, validRangeLteq: { message: '`from` date must be lesser than or equal to `to` date' })

  - v.validate_field(:end, required: { message: 'Please pick end date' })
  - v.validate_field(:end, validRangeGteq: { message: '`to` date must be greater than or equal to `from` date' })

- if @data
  = render(partial: 'shared/report_output', locals: { data: @data })

app/views/administrator_reports/daily_demand_report.html.slim
= breadcrumbs({ 'Admin Reports' => admin_reports_path },
                'Daily Demand Report')

= render(partial: 'shared/flash_message',
         locals: { flash_header: 'Successfully Subscribed' })

- if @data
  = render(partial: 'shared/subscribe_form',
           locals: { target: nil, report_class: 'DailyDemandReport' })

h1 Daily Demand Report

p Graphs the daily trend of sessions established,
  highlighting which time of day users are most active

= render(partial: 'form',
         locals: { report_class: 'DailyDemandReport' })

app/views/administrator_reports/federated_sessions_report.html.slim
= breadcrumbs({ 'Admin Reports' => admin_reports_path },
                'Federated Sessions Report')

= render(partial: 'shared/flash_message',
         locals: { flash_header: 'Successfully Subscribed' })

- if @data
  = render(partial: 'shared/subscribe_form',
           locals: { target: nil, report_class: 'FederatedSessionsReport' })

h1 Federated Sessions Report

p Graphs the hourly number of sessions established

= render(partial: 'form',
         locals: { report_class: 'FederatedSessionsReport' })

app/views/administrator_reports/federation_growth_report.html.slim
= breadcrumbs({ 'Admin Reports' => admin_reports_path },
                'Federation Growth Report')

= render(partial: 'shared/flash_message',
         locals: { flash_header: 'Successfully Subscribed' })

= render(partial: 'shared/subscribe_form',
         locals: { target: nil, report_class: 'FederationGrowthReport' })

h1 Federation Growth Report

p Shows the growth of the federation within a time range, in number of
  Organisations, Service Providers, Identity Providers and Rapid Connect
  Services

= render(partial: 'form',
         locals: { report_class: 'FederationGrowthReport' })

app/views/administrator_reports/identity_provider_utilization_report.html.slim
= breadcrumbs({ 'Admin Reports' => admin_reports_path },
                'Identity Provider Utilization Report')

= render(partial: 'shared/flash_message',
         locals: { flash_header: 'Successfully Subscribed' })

- if @data
  = render(partial: 'shared/subscribe_form',
           locals: { target: nil,
                     report_class: 'IdentityProviderUtilizationReport' })

h1 Identity Provider Utilization Report

p Shows the total number of sessions for each identity provider during the given date range

= render(partial: 'form',
         locals: { report_class: 'IdentityProviderUtilizationReport' })

app/views/administrator_reports/index.html.slim
= breadcrumbs('Admin Reports')

h1 Admin Reports

.list-group
  = link_to(admin_subscriber_registrations_report_path, class: 'list-group-item') do
    h4.list-group-item-heading Subscriber Registrations Report
    p.list-group-item-text
      | Shows the subscriber registration report within a time range, in number of
        Organisations, Service Providers, Identity Providers and Services

  = link_to(admin_federation_growth_report_path, class: 'list-group-item') do
    h4.list-group-item-heading Federation Growth Report
    p.list-group-item-text
      | Shows the federation growth report within a time range in number of
        Organisations, Identity Providers and Services

  = link_to(admin_daily_demand_report_path, class: 'list-group-item') do
    h4.list-group-item-heading Daily Demand Report
    p.list-group-item-text
      | Graphs the daily trend of sessions established,
        highlighting which time of day users are most active

  = link_to(admin_federated_sessions_report_path, class: 'list-group-item') do
    h4.list-group-item-heading Federated Sessions Report
    p.list-group-item-text
      | Graphs the hourly number of sessions established

  = link_to(admin_identity_provider_utilization_report_path, class: 'list-group-item') do
    h4.list-group-item-heading Identity Provider Utilization Report
    p.list-group-item-text
      | Shows the total number of sessions for each identity provider during the given date range

  = link_to(admin_service_provider_utilization_report_path, class: 'list-group-item') do
    h4.list-group-item-heading Service Provider Utilization Report
    p.list-group-item-text
      | Shows the total number of sessions for each service provider during the given date range

app/views/administrator_reports/service_provider_utilization_report.html.slim
= breadcrumbs({ 'Admin Reports' => admin_reports_path },
                'Service Provider Utilization Report')

= render(partial: 'shared/flash_message',
         locals: { flash_header: 'Successfully Subscribed' })

- if @data
  = render(partial: 'shared/subscribe_form',
           locals: { target: nil,
                     report_class: 'ServiceProviderUtilizationReport' })

h1 Service Provider Utilization Report

p Shows the total number of sessions for each service provider during the given date range

= render(partial: 'form',
         locals: { report_class: 'ServiceProviderUtilizationReport' })

app/views/administrator_reports/subscriber_registrations_report.html.slim
= breadcrumbs({ 'Admin Reports' => admin_reports_path },
                'Subscriber Registrations Report')

= render(partial: 'shared/flash_message',
       locals: { flash_header: 'Successfully Subscribed' })

- if @data
  = render(partial: 'shared/subscribe_form',
           locals: { target: @identifier,
                     report_class: 'SubscriberRegistrationsReport' })

h1 Subscriber Registrations Report

p Shows the subscriber registration report within a time range, in number of
  Organisations, Service Providers, Identity Providers and Services

- identifiers = ['organizations', 'identity_providers',
                 'service_providers', 'rapid_connect_services', 'services']

= form_tag({}, id: 'report-form') do
  = field_block do
    = label_tag(:identifier) do
      = 'Subscriber Identifiers'

    - options = identifiers.map { |i| [i.titleize,  i] }.sort
    - options.unshift(['Please select', ''])

    = select_tag(:identifier, options_for_select(options, @identifier))

  = button_tag(type: 'submit', class: 'btn-lg btn-primary') do
    => icon_tag('ok')
    | Generate

= validate_form('#report-form', nil) do |v|
  - v.validate_field(:identifier, required: { message: 'This field is required' })

- if @data
  = render(partial: 'shared/report_output', locals: { data: @data })