config/routes.rb
# frozen_string_literal: true

require 'api_constraints'

Rails.application.routes.draw do
  mount RapidRack::Engine => '/auth'

  get '/dashboard' => 'dashboard#index', :as => 'dashboard'
  root to: 'welcome#index'
  get 'health' => 'health#show'
  # Browsers often request /favicon.ico. This controller redirects to the actual favicon.
  resource :favicon, only: :show

  scope '/federation_reports' do
    get 'federation_growth_report' => 'federation_reports#federation_growth_report',
        :as => :public_federation_growth_report

    get 'federated_sessions_report' => 'federation_reports#federated_sessions_report',
        :as => :public_federated_sessions_report

    get 'daily_demand_report' => 'federation_reports#daily_demand_report', :as => :public_daily_demand_report
  end

  scope '/compliance_reports' do
    def match_report(prefix, name, http_verbs)
      match "/#{prefix}_#{name}", to: "compliance_reports##{prefix}_#{name}", via: http_verbs, as: :"#{prefix}_#{name}"
    end

    match_report('service_provider', 'compatibility_report', %i[get post])
    match_report('identity_provider', 'attributes_report', :get)
    match_report('attribute', 'identity_providers_report', %i[get post])
    match_report('attribute', 'service_providers_report', %i[get post])
  end

  get '/admin_reports' => 'administrator_reports#index', :as => :admin_reports

  scope '/admin_reports' do
    def match_report(name, http_verbs)
      match "/#{name}", to: "administrator_reports##{name}", via: http_verbs, as: :"admin_#{name}"
    end

    match_report('subscriber_registrations_report', %i[get post])
    match_report('federation_growth_report', %i[get post])
    match_report('daily_demand_report', %i[get post])
    match_report('federated_sessions_report', %i[get post])
    match_report('identity_provider_utilization_report', %i[get post])
    match_report('service_provider_utilization_report', %i[get post])
  end

  get '/subscriber_reports' => 'subscriber_reports_dashboard#index', :as => :subscriber_reports

  scope '/subscriber_reports' do
    def match_report(prefix, name, http_verbs)
      match "/#{prefix}_#{name}", to: "#{prefix}_reports##{name}", via: http_verbs, as: :"#{prefix}_#{name}"
    end

    match_report('identity_provider', 'sessions_report', %i[get post])
    match_report('identity_provider', 'daily_demand_report', %i[get post])
    match_report('identity_provider', 'destination_services_report', %i[get post])

    match_report('service_provider', 'sessions_report', %i[get post])
    match_report('service_provider', 'daily_demand_report', %i[get post])
    match_report('service_provider', 'source_identity_providers_report', %i[get post])
  end

  get 'automated_report/:identifier', to: 'automated_report_instances#show', as: :automated_report

  scope '/automated_reports' do
    get '/' => 'automated_reports#index', :as => :automated_reports
    post '/' => 'automated_reports#subscribe'
    delete '/:identifier' => 'automated_reports#destroy'
  end
end

RapidRack::Engine.routes.draw do
  opts = Rails.application.config.reporting_service.rapid_connect[:rack]
  authenticator = opts[:authenticator].constantize.new(opts)

  mount authenticator => ''
end

app/controllers/compliance_reports_controller.rb
# frozen_string_literal: true

class ComplianceReportsController < ApplicationController
  def service_provider_compatibility_report
    public_action
    @objects_list = ServiceProvider.active
    @entity_id = params[:entity_id]

    return unless @entity_id

    report = ServiceCompatibilityReport.new(@entity_id)
    @data = JSON.generate(report.generate)
  end

  def identity_provider_attributes_report
    public_action
    @objects_list = IdentityProvider.active
    report = IdentityProviderAttributesReport.new
    @data = JSON.generate(report.generate)
  end

  def attribute_identity_providers_report
    public_action
    @name = params[:name]
    @objects_list = SAMLAttribute.all

    return unless @name

    report = ProvidedAttributeReport.new(@name)
    @data = JSON.generate(report.generate)
  end

  def attribute_service_providers_report
    public_action
    @name = params[:name]
    @objects_list = SAMLAttribute.all

    return unless @name

    report = RequestedAttributeReport.new(@name)
    @data = JSON.generate(report.generate)
  end
end

app/views/compliance_reports/_form.html.slim
= form_tag({}, id: 'report-form') do
  = field_block do
    = label_tag(:name) do
      = "#{object_type}s"

    - options = @objects_list.map { |obj| [obj.name, obj.name] }.sort_by { |a| a[0].downcase }
    - options.unshift(['Please select', ''])

    = select_tag(:name, options_for_select(options, @name))

  = button_tag(type: 'submit', class: 'btn-lg btn-primary') do
    => icon_tag('ok')
    | Generate

= validate_form('#report-form', nil) do |v|
  - v.validate_field(:name, required: { message: 'This field is required' })

- if @data
  = render(partial: 'shared/report_output', locals: { data: @data })

app/views/compliance_reports/attribute_identity_providers_report.html.slim
= breadcrumbs({ 'Dashboard' => dashboard_path },
                'Single Attribute Identity Providers Report')

= render(partial: 'shared/flash_message',
       locals: { flash_header: 'Successfully Subscribed' })

- if @data
  = render(partial: 'shared/subscribe_form',
           locals: { target: @name, report_class: 'ProvidedAttributeReport' })

h1 Single Attribute IdPs Report

p Describes support for an attribute among the federation's
  Identity Providers

= render(partial: 'form', locals: { object_type: 'Attribute' })

app/views/compliance_reports/attribute_service_providers_report.html.slim
= breadcrumbs({ 'Dashboard' => dashboard_path },
                'Single Attribute Service Providers Report')

= render(partial: 'shared/flash_message',
       locals: { flash_header: 'Successfully Subscribed' })

- if @data
  = render(partial: 'shared/subscribe_form',
           locals: { target: @name, report_class: 'RequestedAttributeReport' })

h1 Single Attribute SPs Report

p Describes Service Providers' requests for a specific attribute, and
  whether they have marked the attribute as required

= render(partial: 'form', locals: { object_type: 'Attribute' })

app/views/compliance_reports/identity_provider_attributes_report.html.slim
= breadcrumbs({ 'Dashboard' => dashboard_path },
                'Identity Provider Attributes Report')

= render(partial: 'shared/flash_message',
         locals: { flash_header: 'Successfully Subscribed' })

= render(partial: 'shared/subscribe_form',
         locals: { target: nil, report_class: 'IdentityProviderAttributesReport' })

h1 Identity Provider Attributes Report

p Graphs the number of attributes which are supported by each Identity
  Provider in the federation

= render(partial: 'shared/report_output', locals: { data: @data })

app/views/compliance_reports/service_provider_compatibility_report.html.slim
= breadcrumbs({ 'Dashboard' => dashboard_path },
                'Service Compatibility Report')


= render(partial: 'shared/flash_message',
       locals: { flash_header: 'Successfully Subscribed' })

- if @data
  = render(partial: 'shared/subscribe_form',
           locals: { target: @entity_id,
                     report_class: 'ServiceCompatibilityReport' })

h1 Service Compatibility Report

p Highlights Identity Providers' ability to meet the attribute
  requirements of a federated service

= form_tag({}, id: 'report-form') do
  = field_block do
    = label_tag(:entity_id) do
      | Service Providers

    - options = @objects_list.map { |sp| [sp.name, sp.entity_id] }.sort_by { |a| a[0].downcase }
    - options.unshift(['Please select', ''])

    = select_tag(:entity_id, options_for_select(options, @entity_id))

  = button_tag(type: 'submit', class: 'btn-lg btn-primary') do
    => icon_tag('ok')
    | Generate

= validate_form('#report-form', nil) do |v|
  - v.validate_field(:entity_id, required: { message: 'This field is required' })

- if @data
  = render(partial: 'shared/report_output', locals: { data: @data })